import { Environment } from "@fractalwallet/types";

const {
  REACT_APP_FRACTAL_WEBSITE_HOSTNAME: FRACTAL_WEBSITE_HOSTNAME = "",
  REACT_APP_ERC20_FCL_CONTRACT: ERC20_FCL_CONTRACT = "",
  REACT_APP_ERC20_FCL_ETH_LP_CONTRACT: ERC20_FCL_ETH_LP_CONTRACT = "",
  REACT_APP_CLAIMS_REGISTRY_CONTRACT: CLAIMS_REGISTRY_CONTRACT = "",
  REACT_APP_STAKING_FCL_CONTRACT: STAKING_FCL_CONTRACT = "",
  REACT_APP_STAKING_FCL_ETH_LP_CONTRACT: STAKING_FCL_ETH_LP_CONTRACT = "",
} = process.env;

const environment: Environment = {
  FRACTAL_WEBSITE_HOSTNAME,
  CONTRACTS: {
    ERC_20_CONTRACTS: {
      FCL: ERC20_FCL_CONTRACT,
      FCL_ETH_LP: ERC20_FCL_ETH_LP_CONTRACT,
    },
    CLAIMS_REGISTRY_CONTRACT,
    STAKING_CONTRACTS: {
      FCL: STAKING_FCL_CONTRACT,
      FCL_ETH_LP: STAKING_FCL_ETH_LP_CONTRACT,
    },
  },
};

export default environment;
