enum ConnectionTypes {
  GET_VERIFICATION_REQUEST_BACKGROUND = "GET_VERIFICATION_REQUEST_BACKGROUND",
  SETUP_PLUGIN_BACKGROUND = "SETUP_PLUGIN_BACKGROUND",
  VERIFY_CONNECTION_BACKGROUND = "VERIFY_CONNECTION_BACKGROUND",
  GET_BACKEND_SESSIONS_INPAGE = "GET_BACKEND_SESSIONS_INPAGE",
  WEBPAGE_VIEW = "WEBPAGE_VIEW",
}

export default ConnectionTypes;
