enum StakingStatus {
  START = "START",
  APPROVAL_PENDING = "APPROVAL_PENDING",
  APPROVED = "APPROVED",
  STAKING_PENDING = "STAKING_PENDING",
  STAKED = "STAKED",
  WITHDRAW_PENDING = "WITHDRAW_PENDING",
}

export default StakingStatus;
