enum ConnectionTypes {
  CONFIRM_CREDENTIAL = "CONFIRM_CREDENTIAL",
  COMMIT_CREDENTIAL = "COMMIT_CREDENTIAL",
  GET_ACCOUNT_ADDRESS = "GET_ACCOUNT_ADDRESS",
  REQUEST_CREDENTIAL = "REQUEST_CREDENTIAL",
  VERIFY_EXTENSION_CONNECTION = "VERIFY_EXTENSION_CONNECTION",
}

export default ConnectionTypes;
