enum ConnectionTypes {
  CREDENTIAL_STORE_REQUEST = "CREDENTIAL_STORE_REQUEST",
  CREDENTIAL_STORE_COMMIT = "CREDENTIAL_STORE_COMMIT",
  GET_ACCOUNT_ADDRESS = "GET_ACCOUNT_ADDRESS",
  HAS_CREDENTIAL_REQUEST = "HAS_CREDENTIAL_REQUEST",
  SETUP_PLUGIN_REQUEST = "SETUP_PLUGIN_REQUEST",
  STAKE_COMMIT = "STAKE_COMMIT",
  STAKE_REQUEST = "STAKE_REQUEST",
  VERIFY_CONNECTION_REQUEST = "VERIFY_CONNECTION_REQUEST",
  WITHDRAW_REQUEST = "WITHDRAW_REQUEST",
  WITHDRAW_COMMIT = "WITHDRAW_COMMIT",
}

export default ConnectionTypes;
