enum ConnectionTypes {
  GET_ACCOUNT_ADDRESS = "GET_ACCOUNT_ADDRESS",
  HAS_CREDENTIAL = "HAS_CREDENTIAL",
  VERIFY_CONNECTION = "VERIFY_CONNECTION",
  SETUP_PLUGIN = "SETUP_PLUGIN",
}

export default ConnectionTypes;
